import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
const html=readFileSync("index.html","utf8"), main=readFileSync("src/browser/main.ts","utf8"), controller=readFileSync("src/browser/dashboard-controller.ts","utf8"), router=readFileSync("src/browser/task-router.ts","utf8"), db=readFileSync("src/data/indexeddb.ts","utf8"), workflow=readFileSync("src/core/business-world-workflow.ts","utf8"), approval=readFileSync("src/core/demo-approval.ts","utf8"), seed=readFileSync("src/demo/seed.ts","utf8");
describe("Business World browser production contract",()=>{
  it("stays fresh until explicit assignment",()=>{expect(html).toContain('id="task-input" value=""');expect(html).toContain('id="work-count" class="meta">0 tasks');expect(controller).not.toMatch(/assign\(\)\s*;\s*$/m);expect(html).toContain("Nothing runs until you press Assign.");
    expect(controller).toContain("await initializeBusinessWorld()");
    expect(controller).toContain("resetWorkspace(false)");});
  it("uses repository modules and a thin main entry",()=>{expect(main).toContain("bootstrapDashboard");expect(main.length).toBeLessThan(1000);expect(controller).toContain("IndexedDbBusinessRepository");expect(controller).toContain("IndexedDbWorkRepository");expect(db).toContain('customers:"customers"');expect(db).toContain('taskEvents:"taskEvents"');expect(db).toContain('evidence:"evidence"');});
  it("supports capability routing beyond ACME",()=>{for(const intent of ["customer.lookup","receivables.review","payments.reconcile","followup.prepare","exceptions.review","portfolio.overdue","daily.brief"])expect(router).toContain(intent);expect(html).toContain("Check Beacon account");expect(router).toContain("unsupported");});
  it("separates employee activity from seeded business snapshot",()=>{expect(html).toContain("Employee Activity");expect(html).toContain("Business Snapshot · Demo Business Data");expect(html).toContain('id="snapshot-open"');expect(html).toContain('id="kpi-completed">0');});
  it("has real Customers, History, scenario and reset surfaces",()=>{expect(html).toContain('id="customers-view"');expect(html).toContain('id="history-view"');expect(html).toContain("Demo Scenario Library");expect(html).toContain('id="restore-business-data"');expect(html).toContain('id="reset-entire-demo"');expect(html).toContain('id="clear-history"');});
  it("keeps approval explicitly local and observable",()=>{expect(controller).toContain("Local Demo Simulation");expect(controller).toContain("No external system changed");expect(approval).toContain("APPROVED");expect(approval).toContain("RESUMED");expect(approval).toContain("DraftAction");});
  it("keeps completion verification-gated before Gateway summarization",()=>{expect(workflow).toContain('event("VERIFYING"');expect(workflow).toContain('taskStatus(result.status)');const gate=controller.indexOf('result.task.status!=="completed"||result.verification.status!=="PASS"');const call=controller.indexOf("gateway.chat");expect(gate).toBeGreaterThanOrEqual(0);expect(call).toBeGreaterThan(gate);});
  it("uses versioned seed and local IndexedDB labels",()=>{expect(seed).toContain('DEMO_SEED_VERSION = "demo-business-v1"');expect(seed).toContain('DEMO_COMPANY_NAME = "Northstar Distribution Pte Ltd"');expect(html).toContain("Local IndexedDB");expect(controller).toContain("Demo Business Data");});
  it("preserves mobile/accessibility and SVG constraints",()=>{expect(html).toContain('class="skip-link"');expect(html).toContain('class="mobile-bottom-nav"');expect(html).toContain('id="work-cards"');expect(html).toContain(":focus-visible");expect(html).not.toMatch(/font-size:\s*(8|9|10|11)px/);expect(main).toContain("hydrateSvgIcons");});
});
