import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
const html=readFileSync("index.html","utf8"),main=readFileSync("src/browser/main.ts","utf8"),controller=readFileSync("src/browser/dashboard-controller.ts","utf8"),router=readFileSync("src/browser/router.ts","utf8"),pwa=readFileSync("src/pwa/client.ts","utf8"),i18n=readFileSync("src/i18n/index.ts","utf8");
describe("deterministic loading presentation contract",()=>{
  it("starts in an explicit busy boot state and hides false empty app content",()=>{expect(html).toContain('data-app-state="booting"');expect(html).toContain('id="app-bootstrap"');expect(html).toContain('aria-busy="true"');expect(html).toContain('id="app-shell" aria-hidden="true"');expect(main).toContain('setAppState("ready")');expect(main).toContain('setAppState("error"');});
  it("hydrates Business World before initial route application",()=>{const boot=controller.slice(controller.indexOf('export async function bootstrapDashboard'));const init=boot.indexOf('await initializeBusinessWorld()'),hydrate=boot.indexOf('await renderAll()'),start=boot.indexOf('router.start({initialApply:false})'),route=boot.indexOf('await applyRoute(parseHash())');expect(init).toBeGreaterThan(0);expect(init).toBeLessThan(hydrate);expect(hydrate).toBeLessThan(start);expect(start).toBeLessThan(route);expect(router).toContain('initialApply?:boolean');});
  it("provides route skeletons without fake percentage progress",()=>{for(const key of ['loading.work','loading.inbox','loading.customers','loading.customer','loading.history','loading.approvals','loading.approval','loading.task'])expect(controller).toContain(key);expect(controller).toContain('route-loading');expect(controller).not.toMatch(/loading[^\n]{0,80}%/);expect(html).toContain('prefers-reduced-motion:reduce');});
  it("uses real persisted task events for execution activity",()=>{expect(controller).toContain('onEvent:async(event)=>');expect(controller).toContain('renderCurrentActivityFromEvents');expect(controller).toContain('projectTaskActivity(events)');});
  it("guards assignment and human decision mutations against duplicate submission",()=>{expect(controller).toContain('if(running||routing)return');expect(controller).toContain('mutationKeys.has(key)');expect(controller).toContain('aria-busy');expect(controller).toContain('loading.savingDecision');expect(controller).toContain('loading.savingAction');});
  it("keeps Gateway loading scoped to Employee Summary",()=>{expect(controller).toContain('void createManagerSummary(result).then');expect(controller).toContain('feedback.preparingSummary');expect(controller).toContain('feedback.preparingVerified');});
  it("uses explicit i18n DOM bindings while keeping reverse lookup compatibility",()=>{expect(i18n).toContain('data-i18n-placeholder');expect(i18n).toContain('data-i18n-aria-label');expect(html).toContain('data-i18n-placeholder="home.assignPlaceholder"');expect(html).toContain('data-i18n-placeholder="customers.search"');expect(html).toContain('data-i18n="pwa.updateNow"');});
  it("makes PWA version/update state finite rather than indefinitely loading",()=>{expect(pwa).toContain('settings.checkingUpdate');expect(pwa).toContain('settings.updateUnavailable');expect(pwa).toContain('settings.upToDate');expect(pwa).toContain('settings.updateReady');});
});
