import { DEMO_COMPANY_NAME, DEMO_SNAPSHOT_DATE } from "../demo/seed";
import { IndexedDbBusinessRepository } from "../data/business-repository";
import { IndexedDbWorkRepository } from "../data/work-repository";
import { clearTaskHistory, initializeBusinessWorld, resetEntireDemo, restoreSampleBusinessData } from "../data/indexeddb";
import type { BusinessApproval, BusinessInboxItem, BusinessTask } from "../data/models";
import { approveLocalDemo, createLocalDemoApproval, rejectLocalDemo } from "../core/demo-approval";
import { reviewCustomer, runBusinessWorldTask, type BusinessWorldResult } from "../core/business-world-workflow";
import { createDemoGatewayClient, DemoGatewayError, DemoGatewayRateLimitError } from "../shared/demo-gateway-client";
import { routeDashboardTask } from "./task-router";
import { svgIcon } from "./icons";

const $=<T extends Element>(selector:string)=>document.querySelector<T>(selector)!;
const form=$<HTMLFormElement>("#task-form"), taskInput=$<HTMLInputElement>("#task-input"), assignButton=$<HTMLButtonElement>("#assign-task");
const suggestionButtons=[...document.querySelectorAll<HTMLButtonElement>(".quick-task,.scenario-task")];
const workBody=$<HTMLTableSectionElement>("#work-body"), workCards=$<HTMLElement>("#work-cards"), workCount=$<HTMLElement>("#work-count"), historyCount=$<HTMLElement>("#history-count");
const detailState=$<HTMLElement>("#detail-state"), businessResult=$<HTMLElement>("#business-result"), businessMeta=$<HTMLElement>("#business-meta");
const verificationList=$<HTMLElement>("#verification-list"), verificationCount=$<HTMLElement>("#verification-count"), rawEvidence=$<HTMLPreElement>("#raw-evidence"), evidenceDetails=$<HTMLDetailsElement>("#evidence-details");
const aiSummary=$<HTMLElement>("#ai-summary"), gatewayStatus=$<HTMLElement>("#gateway-status"), gatewayConnection=$<HTMLElement>("#gateway-connection"), currentActivity=$<HTMLElement>("#current-activity");
const employeeMode=$<HTMLElement>("#employee-mode"), lastUpdated=$<HTMLElement>("#last-updated"), composerFeedback=$<HTMLElement>("#composer-feedback");
const inboxList=$<HTMLElement>("#inbox-list"), inboxBadge=$<HTMLElement>("#inbox-badge"), approvalList=$<HTMLElement>("#approval-list"), approvalBadge=$<HTMLElement>("#approval-badge");
const kpiCompleted=$<HTMLElement>("#kpi-completed"), kpiCustomers=$<HTMLElement>("#kpi-customers"), kpiApprovals=$<HTMLElement>("#kpi-approvals"), kpiAttention=$<HTMLElement>("#kpi-attention");
const snapshotOpen=$<HTMLElement>("#snapshot-open"), snapshotOverdue=$<HTMLElement>("#snapshot-overdue"), snapshotRisk=$<HTMLElement>("#snapshot-risk"), snapshotExceptions=$<HTMLElement>("#snapshot-exceptions"), snapshotDate=$<HTMLElement>("#snapshot-date");
const briefTitle=$<HTMLElement>("#brief-title"), briefCopy=$<HTMLElement>("#brief-copy"), briefList=$<HTMLElement>("#brief-list"), briefNote=$<HTMLElement>("#brief-note");
const customerSearch=$<HTMLInputElement>("#customer-search"), customerList=$<HTMLElement>("#customer-list"), customerDetail=$<HTMLElement>("#customer-detail"), historyList=$<HTMLElement>("#history-list");
const trustDrawer=$<HTMLElement>("#trust-drawer"), drawerOverlay=$<HTMLElement>("#drawer-overlay"), openTrustDrawerButton=$<HTMLButtonElement>("#open-trust-drawer"), closeTrustDrawerButton=$<HTMLButtonElement>("#close-trust-drawer");
const datasetSnapshot=$<HTMLElement>("#dataset-snapshot"), businessDataDetail=$<HTMLElement>("#business-data-detail");

const business=new IndexedDbBusinessRepository(); const work=new IndexedDbWorkRepository(); const gateway=createDemoGatewayClient({origin:window.location.origin});
let running=false; let latestEvidence=""; let tasks:BusinessTask[]=[]; let inbox:BusinessInboxItem[]=[]; let approvals:BusinessApproval[]=[];
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));
const money=(n:number)=>`SGD ${n.toLocaleString("en-SG")}`;
const dateLabel=()=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${DEMO_SNAPSHOT_DATE}T00:00:00Z`));
const statusLabel=(s:BusinessTask["status"])=>({created:"Ready",running:"Running","needs-review":"Needs Review","needs-approval":"Needs Approval",completed:"Completed",failed:"Failed",blocked:"Blocked"}[s]);
const statusClass=(s:BusinessTask["status"])=>s==="completed"?"completed":s==="needs-review"?"review":s==="needs-approval"?"approval":s==="failed"?"failed":s==="blocked"?"blocked":"running";
function setEmployeeMode(mode:string){employeeMode.textContent=mode;lastUpdated.textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}
function setDetail(task?:BusinessTask){if(!task){detailState.textContent="Ready";detailState.className="status-chip running";return;}detailState.textContent=statusLabel(task.status);detailState.className=`status-chip ${statusClass(task.status)}`;}
function resetWorkspace(focus=true){taskInput.value="";composerFeedback.textContent="";setDetail();businessMeta.textContent="No verified result yet";businessResult.innerHTML='<p class="approval-empty">Assign a task to see Alex\'s verified business result.</p>';verificationCount.textContent="0 / 0";verificationList.innerHTML=`<li><span class="check-icon">${svgIcon("circle")}</span><div>Waiting for verified evidence.</div></li>`;rawEvidence.textContent="";latestEvidence="";evidenceDetails.open=false;aiSummary.textContent="Generated only after deterministic verification passes.";gatewayStatus.textContent="Demo Gateway not called yet.";currentActivity.innerHTML=`<li><span class="activity-icon idle">${svgIcon("circle")}</span><div class="activity-copy"><strong>Waiting for work</strong><small>Assign a task to Alex.</small></div></li>`;setEmployeeMode("Available");if(focus)taskInput.focus();}
async function refreshData(){[tasks,inbox,approvals]=await Promise.all([work.listTaskHistory(),work.listInbox(),work.listApprovals()]);}
async function renderKpis(){const completed=tasks.filter(t=>t.status==="completed");const customers=new Set(completed.map(t=>t.customerId).filter(Boolean));const pending=approvals.filter(a=>a.state==="pending").length;const openInbox=inbox.filter(i=>i.status!=="resolved").length;kpiCompleted.textContent=String(completed.length);kpiCustomers.textContent=String(customers.size);kpiApprovals.textContent=String(pending);kpiAttention.textContent=String(openInbox+pending);const snap=await business.getBusinessSnapshot();snapshotOpen.textContent=money(snap.openReceivables);snapshotOverdue.textContent=String(snap.overdueInvoices);snapshotRisk.textContent=String(snap.customersAtRisk);snapshotExceptions.textContent=String(snap.exceptions);snapshotDate.textContent=`Snapshot ${dateLabel()}`;}
function renderWork(){workCount.textContent=`${tasks.length} ${tasks.length===1?"task":"tasks"}`;historyCount.textContent=workCount.textContent;if(!tasks.length){workBody.innerHTML='<tr><td class="empty-row" colspan="5">Assign a task to start Alex\'s work queue.</td></tr>';workCards.innerHTML='<div class="approval-empty">No tasks yet.</div>';return;}workBody.innerHTML=tasks.slice(0,8).map(t=>`<tr><td><div class="task-name">${esc(t.title)}</div><div class="task-context">${esc(t.intent)}</div></td><td>${esc(t.customerQuery??DEMO_COMPANY_NAME)}</td><td><span class="status-chip ${statusClass(t.status)}">${statusLabel(t.status)}</span></td><td>${esc(t.verification?`${t.verification.passed}/${t.verification.total} verified`:t.status)}</td><td><button class="link-btn inspect-task" data-task-id="${t.id}" type="button">View</button></td></tr>`).join("");workCards.innerHTML=tasks.slice(0,8).map(t=>`<article class="work-card"><div class="work-card-head"><h3>${esc(t.title)}</h3><span class="status-chip ${statusClass(t.status)}">${statusLabel(t.status)}</span></div><dl><dt>Intent</dt><dd>${esc(t.intent)}</dd><dt>Context</dt><dd>${esc(t.customerQuery??DEMO_COMPANY_NAME)}</dd><dt>Created</dt><dd>${new Date(t.createdAt).toLocaleString()}</dd></dl><button class="link-btn inspect-task" data-task-id="${t.id}" type="button">View task</button></article>`).join("");}
function inboxActions(item:BusinessInboxItem){if(item.status==="open")return`<button class="secondary-btn inbox-action" data-action="investigate" data-id="${item.id}">Investigate</button>`;if(item.status==="investigating")return`<button class="secondary-btn inbox-action" data-action="resolve" data-id="${item.id}">Resolve</button><button class="secondary-btn inbox-action" data-action="escalate" data-id="${item.id}">Escalate</button>`;return`<span class="status-chip ${item.status==="resolved"?"completed":"review"}">${item.status}</span>`;}
function renderInbox(){const visible=inbox.filter(i=>i.status!=="resolved");inboxBadge.textContent=String(visible.length);inboxBadge.classList.toggle("attention",visible.length>0);inboxList.innerHTML=visible.length?visible.slice(0,8).map(i=>`<li><div class="inbox-copy"><strong>${esc(i.title)}</strong><small>${esc(i.detail)} · ${esc(i.severity)} · ${esc(i.status)}</small></div><div>${inboxActions(i)}</div></li>`).join(""):'<li class="approval-empty">No items need attention.</li>';}
function renderApprovals(){const pending=approvals.filter(a=>a.state==="pending");approvalBadge.textContent=String(pending.length);approvalBadge.classList.toggle("attention",pending.length>0);approvalList.innerHTML=approvals.length?approvals.slice(0,5).map(a=>`<article class="approval-scenario"><div><span class="status-chip ${a.state==="pending"?"approval":a.state==="approved"?"completed":"blocked"}">Local Demo Simulation · ${a.state}</span></div><h3>${esc(a.title)}</h3><ul class="approval-facts"><li><b>What:</b> ${esc(a.what)}</li><li><b>Why:</b> ${esc(a.why)}</li><li><b>Affected:</b> ${esc(a.affected)}</li><li><b>Impact:</b> ${esc(a.impact)}</li></ul><div class="approval-simulation-note">No external system changed.</div>${a.state==="pending"?`<div class="approval-actions"><button class="primary-btn approval-action" data-action="approve" data-id="${a.id}">Approve & Resume</button><button class="secondary-btn approval-action" data-action="reject" data-id="${a.id}">Reject</button></div>`:""}</article>`).join(""):'<p><strong>No approvals pending.</strong></p><p>Use the Approval scenario to test pause → decision → resume locally.</p>';}
function renderBrief(){const completed=tasks.filter(t=>t.status==="completed").length;const attention=inbox.filter(i=>i.status!=="resolved").length+approvals.filter(a=>a.state==="pending").length;if(!tasks.length){briefTitle.textContent="Ready for work";briefCopy.textContent=`${DEMO_COMPANY_NAME} is seeded locally. Business exceptions exist, but Alex has completed 0 employee tasks.`;briefList.innerHTML="";briefNote.textContent="Available";return;}briefTitle.textContent=attention?`${attention} item${attention===1?"":"s"} need attention`:"Operations are on track";briefCopy.textContent="Task history and business data are projected from Local IndexedDB.";briefList.innerHTML=`<li>${svgIcon("check")}<b>${completed}</b> completed tasks</li><li>${svgIcon(attention?"alert":"check")}<b>${attention}</b> need attention</li>`;briefNote.textContent=attention?"Manager review needed":"On track";}
async function renderHistory(){if(!tasks.length){historyList.innerHTML='<p class="approval-empty">No task history yet.</p>';return;}historyList.innerHTML=tasks.map(t=>`<article class="history-item" data-task-id="${t.id}"><div><h3>${esc(t.title)}</h3><p>${esc(t.intent)} · ${new Date(t.createdAt).toLocaleString()}</p></div><span class="status-chip ${statusClass(t.status)}">${statusLabel(t.status)}</span><button class="link-btn history-inspect" data-task-id="${t.id}" type="button">Inspect timeline</button><div class="timeline" id="timeline-${t.id}" hidden></div></article>`).join("");}
async function renderCustomers(filter=""){const customers=(await business.listCustomers()).filter(c=>!filter||`${c.name} ${c.code} ${c.aliases.join(" ")}`.toLowerCase().includes(filter.toLowerCase()));customerList.innerHTML=customers.map(c=>`<button class="entity-row customer-row" data-id="${c.id}" type="button"><strong>${esc(c.name)}</strong><small>${esc(c.code)} · Risk ${c.risk}</small></button>`).join("");if(!customers.length)customerDetail.innerHTML='<p class="approval-empty">No customers match the search.</p>';}
async function showCustomer(id:string){const customer=await business.getCustomer(id);if(!customer)return;const [review,related]=await Promise.all([reviewCustomer(business,customer),work.listTaskHistory()]);customerDetail.innerHTML=`<h3>${esc(customer.name)}</h3><p>${esc(customer.code)} · ${esc(customer.status)} · Risk ${esc(customer.risk)}</p><div class="entity-summary"><div><span>Outstanding</span><strong>${money(review.outstandingTotal)}</strong></div><div><span>Open invoices</span><strong>${review.open.length}</strong></div><div><span>Credit limit</span><strong>${money(customer.creditLimit)}</strong></div></div><h4>Invoices</h4><table class="mini-table"><thead><tr><th>Invoice</th><th>Due</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>${review.rows.map(r=>`<tr><td>${esc(r.invoice.number)}</td><td>${esc(r.invoice.dueOn)}</td><td>${money(r.outstanding)}</td><td>${esc(r.invoice.status)}</td></tr>`).join("")}</tbody></table><h4>Payments</h4><table class="mini-table"><tbody>${review.payments.map(p=>`<tr><td>${esc(p.reference)}</td><td>${money(p.amount)}</td><td>${esc(p.status)}</td></tr>`).join("")||'<tr><td>No payments</td></tr>'}</tbody></table><h4>Related tasks</h4><p>${related.filter(t=>t.customerId===customer.id).map(t=>esc(t.title)).join(" · ")||"No related tasks yet."}</p>`;document.querySelectorAll(".customer-row").forEach(el=>el.classList.toggle("active",(el as HTMLElement).dataset.id===id));}
async function renderAll(){await refreshData();renderWork();renderInbox();renderApprovals();renderBrief();await Promise.all([renderKpis(),renderHistory(),renderCustomers(customerSearch.value)]);}
function safeMarkdown(value:string){const escaped=esc(value);return escaped.replace(/^###?\s+(.+)$/gm,"<h3>$1</h3>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/^[-*]\s+(.+)$/gm,"<div>• $1</div>").replace(/\n/g,"<br>");}
function renderSummary(summary:Record<string,unknown>){const customer=summary.customer as any;if(customer&&typeof customer==="object"){const out=Number(summary.outstandingTotal??0);return`<div class="result-grid"><div class="result-cell"><span>Customer</span><strong>${esc(customer.name??customer.id)}</strong></div><div class="result-cell"><span>Outstanding</span><strong>${money(out)}</strong></div><div class="result-cell"><span>Open invoices</span><strong>${esc(summary.outstandingInvoices??0)}</strong></div><div class="result-cell"><span>Follow-ups</span><strong>${Array.isArray(summary.followUps)?summary.followUps.length:0}</strong></div></div>`;}if("totalOverdueCustomers" in summary)return`<div class="result-grid"><div class="result-cell"><span>Overdue customers</span><strong>${esc(summary.totalOverdueCustomers)}</strong></div><div class="result-cell"><span>Total overdue</span><strong>${money(Number(summary.totalOverdueAmount??0))}</strong></div><div class="result-cell"><span>Exceptions</span><strong>${esc(summary.exceptionsRequiringReview)}</strong></div></div><h4>Highest priority accounts</h4><div>${(summary.highestPriority as any[]??[]).map(a=>`<p><strong>${esc(a.customer)}</strong> · ${money(a.overdueAmount)} · ${a.maxDaysOverdue} days</p>`).join("")}</div><h4>Upcoming due accounts</h4><div>${(summary.upcomingDueAccounts as any[]??[]).map(a=>`<p><strong>${esc(a.customer)}</strong> · ${money(a.amount)} · ${a.invoices} invoice${a.invoices===1?"":"s"}</p>`).join("")||"<p>None in the next 14 days.</p>"}</div>`;if("paymentExceptions" in summary)return`<h4>Payment exceptions</h4>${(summary.paymentExceptions as any[]??[]).map(e=>`<div class="attention-box"><strong>${esc(e.title)}</strong><br>${esc(e.detail)}</div>`).join("")}`;if("exceptions" in summary&&Array.isArray(summary.exceptions))return`<h4>Business exceptions</h4>${(summary.exceptions as any[]).map(e=>`<div class="attention-box"><strong>${esc(e.title)}</strong><br>${esc(e.detail)}</div>`).join("")}`;if("snapshot" in summary){const snap=summary.snapshot as any;return`<div class="result-grid"><div class="result-cell"><span>Open receivables</span><strong>${money(snap.openReceivables)}</strong></div><div class="result-cell"><span>Overdue invoices</span><strong>${snap.overdueInvoices}</strong></div><div class="result-cell"><span>Exceptions</span><strong>${esc(summary.exceptions)}</strong></div><div class="result-cell"><span>Pending approvals</span><strong>${esc(summary.pendingApprovals)}</strong></div></div>`;}return`<pre>${esc(JSON.stringify(summary,null,2))}</pre>`;}
async function renderTaskDetail(taskId:string){const task=await work.getTask(taskId);if(!task)return;const [events,evidence]=await Promise.all([work.listTaskEvents(taskId),work.listEvidence(taskId)]);setDetail(task);businessMeta.textContent=`${task.intent} · ${task.customerQuery??DEMO_COMPANY_NAME}`;businessResult.innerHTML=renderSummary(task.summary??{status:statusLabel(task.status)});verificationCount.textContent=task.verification?`${task.verification.passed} / ${task.verification.total} checks passed`:"0 / 0";const verificationEvidence=evidence.find(e=>e.type==="verification")?.data as any;verificationList.innerHTML=verificationEvidence?.checks?.length?verificationEvidence.checks.map((c:any)=>`<li data-pass="${!!c.passed}"><span class="check-icon">${svgIcon(c.passed?"check":"x")}</span><div><strong>${esc(c.id)}</strong>${c.message?`<div>${esc(c.message)}</div>`:""}</div></li>`).join(""):`<li><span class="check-icon">${svgIcon("circle")}</span><div>No completed verification evidence.</div></li>`;latestEvidence=JSON.stringify(evidence,null,2);rawEvidence.textContent=latestEvidence;const manager=evidence.find(e=>e.type==="manager.summary")?.data as any;aiSummary.innerHTML=manager?.html??(task.status==="completed"?"<p>Verified task complete. Manager summary not available.</p>":"<p>Summary is generated only after verified completion.</p>");gatewayStatus.textContent=manager?.gatewayStatus??"Gateway not called for this task.";currentActivity.innerHTML=events.slice(-7).map(e=>`<li><span class="activity-icon ${e.type==="COMPLETED"?"done":e.type==="FAILED"?"idle":"active"}">${svgIcon(e.type==="COMPLETED"?"check":e.type==="FAILED"?"x":"circle-dot")}</span><div class="activity-copy"><strong>${esc(e.message)}</strong><small>${esc(e.type)} · ${new Date(e.occurredAt).toLocaleTimeString()}</small></div></li>`).join("")||`<li><span class="activity-icon idle">${svgIcon("circle")}</span><div>No task events.</div></li>`;setEmployeeMode(task.status==="needs-approval"||task.status==="needs-review"?"Waiting on manager":task.status==="running"?"Working":"Available");}
async function inspectHistory(taskId:string){const box=$<HTMLElement>(`#timeline-${CSS.escape(taskId)}`);const [events,evidence]=await Promise.all([work.listTaskEvents(taskId),work.listEvidence(taskId)]);box.hidden=!box.hidden;if(box.hidden)return;box.innerHTML=events.map(e=>`<div class="timeline-row"><b>${esc(e.type)}</b><span>${esc(e.message)}</span><span>${new Date(e.occurredAt).toLocaleTimeString()}</span></div>`).join("")+`<div class="timeline-row"><b>Evidence</b><span>${evidence.length} records stored separately</span><span></span></div>`;}
async function createManagerSummary(result:BusinessWorldResult){if(result.task.status!=="completed"||result.verification.status!=="PASS")return;aiSummary.textContent="Verification passed · Preparing manager summary…";gatewayStatus.textContent="Preparing manager summary from verified facts only…";try{const response=await gateway.chat({messages:[{role:"system",content:"You are Alex, an operations employee. Summarize only the supplied verified facts for a manager. Do not invent business facts or completion claims."},{role:"user",content:JSON.stringify({intent:result.task.intent,summary:result.summary,verification:result.verification})}]});const choices=(response as any)?.choices;const text=Array.isArray(choices)&&typeof choices[0]?.message?.content==="string"?choices[0].message.content:"Verified work completed.";const html=safeMarkdown(text);aiSummary.innerHTML=html;gatewayStatus.textContent="Demo Gateway connected · demo-auto · verified facts only";gatewayConnection.textContent="Connected";await work.saveEvidence({id:`evidence-${result.task.id}-manager`,taskId:result.task.id,type:"manager.summary",source:"demo-gateway",createdAt:new Date().toISOString(),data:{html,gatewayStatus:gatewayStatus.textContent}});}catch(error){gatewayConnection.textContent="Unavailable";gatewayStatus.textContent=error instanceof DemoGatewayRateLimitError?error.message:error instanceof DemoGatewayError&&error.status===403?`Gateway Origin is not enabled for ${window.location.origin}. Verified business work still completed locally.`:`AI summary unavailable: ${error instanceof Error?error.message:String(error)}`;aiSummary.textContent="Verified business result is available; manager summary is temporarily unavailable.";}}
async function createRuntimeInboxForReview(task:BusinessTask){if(task.status!=="needs-review")return;const existing=(await work.listInbox()).some(i=>i.relatedEntityId===task.id&&i.type==="ambiguous-customer");if(existing)return;await work.saveInboxItem({id:`inbox-${task.id}`,type:"ambiguous-customer",severity:"warning",relatedEntityType:"customer",relatedEntityId:task.id,createdAt:new Date().toISOString(),status:"open",title:"Customer identity needs review",detail:`${task.customerQuery??"Customer"} could not be resolved uniquely.`});}
async function executeRouted(title:string,intent:any,customerQuery?:string,taskId?:string){running=true;assignButton.disabled=true;suggestionButtons.forEach(b=>b.disabled=true);setEmployeeMode("Working");currentActivity.innerHTML=`<li><span class="activity-icon active">${svgIcon("circle-dot")}</span><div class="activity-copy"><strong>Working on assigned task</strong><small>${esc(intent)}</small></div></li>`;try{const result=await runBusinessWorldTask(business,work,{taskId,title,intent,customerQuery});await createRuntimeInboxForReview(result.task);await renderAll();await renderTaskDetail(result.task.id);await createManagerSummary(result);await renderTaskDetail(result.task.id);}finally{running=false;assignButton.disabled=false;suggestionButtons.forEach(b=>b.disabled=false);}}
async function createBlocked(title:string,reason:string){const now=new Date().toISOString();const task:BusinessTask={id:`task-${Date.now()}`,title,intent:"unsupported",status:"blocked",createdAt:now,updatedAt:now,summary:{reason}};await work.createTask(task);await work.appendTaskEvent({id:`event-${task.id}-created`,taskId:task.id,type:"CREATED",occurredAt:now,message:"Task created"});await work.appendTaskEvent({id:`event-${task.id}-routed`,taskId:task.id,type:"ROUTED",occurredAt:new Date(Date.now()+1).toISOString(),message:"Unsupported capability"});await work.saveEvidence({id:`evidence-${task.id}-blocked`,taskId:task.id,type:"routing.blocked",source:"task-router",createdAt:now,data:{reason}});composerFeedback.textContent=reason;await renderAll();await renderTaskDetail(task.id);}
async function createApprovalScenario(title:string,customerQuery:string){const created=await createLocalDemoApproval(work,{title,customerQuery,snapshotLabel:`Snapshot ${dateLabel()}`});await renderAll();await renderTaskDetail(created.task.id);}
async function decideApproval(id:string,decision:"approve"|"reject"){if(decision==="reject"){const rejected=await rejectLocalDemo(work,id);if(rejected){await renderAll();await renderTaskDetail(rejected.task.id);}return;}const approved=await approveLocalDemo(work,id);if(!approved)return;await renderAll();await executeRouted(approved.task.title,"followup.prepare",approved.task.customerQuery,approved.task.id);}
async function actOnInbox(id:string,action:"investigate"|"resolve"|"escalate"){await work.updateInboxStatus(id,action==="investigate"?"investigating":action==="resolve"?"resolved":"escalated",action==="investigate"?"Investigation opened":action==="resolve"?"Resolved in local demo":"Escalated for manager review");await renderAll();}
async function assign(){if(running)return;const title=taskInput.value.trim();if(!title){composerFeedback.textContent="Enter a task or choose a scenario first.";return;}composerFeedback.textContent="";const routed=routeDashboardTask(title);if(routed.intent==="unsupported"){await createBlocked(title,routed.reason??"Unsupported capability");return;}if(routed.intent==="approval-demo"){await createApprovalScenario(title,routed.customerQuery??"ACME");return;}await executeRouted(title,routed.intent,routed.customerQuery);}
function openDrawer(){trustDrawer.classList.add("open");drawerOverlay.classList.add("open");closeTrustDrawerButton.focus();}
function closeDrawer(){trustDrawer.classList.remove("open");drawerOverlay.classList.remove("open");openTrustDrawerButton.focus();}
async function refreshAfterReset(message:string){await renderAll();resetWorkspace(false);composerFeedback.textContent=message;}

function bindEvents(){form.addEventListener("submit",e=>{e.preventDefault();void assign();});document.querySelectorAll<HTMLButtonElement>(".mobile-section-toggle").forEach(button=>button.addEventListener("click",()=>{const section=document.getElementById(button.dataset.target??"");if(!section)return;const open=section.classList.toggle("mobile-open");button.textContent=open?"Close":"Open";}));suggestionButtons.forEach(button=>button.addEventListener("click",()=>{taskInput.value=button.dataset.task??"";composerFeedback.textContent="Scenario added. Review it, then press Assign.";taskInput.focus();}));document.addEventListener("click",e=>{const el=e.target as HTMLElement;const inspect=el.closest<HTMLButtonElement>(".inspect-task");if(inspect?.dataset.taskId)void renderTaskDetail(inspect.dataset.taskId);const hist=el.closest<HTMLButtonElement>(".history-inspect");if(hist?.dataset.taskId)void inspectHistory(hist.dataset.taskId);const cust=el.closest<HTMLButtonElement>(".customer-row");if(cust?.dataset.id)void showCustomer(cust.dataset.id);const inboxButton=el.closest<HTMLButtonElement>(".inbox-action");if(inboxButton?.dataset.id&&inboxButton.dataset.action)void actOnInbox(inboxButton.dataset.id,inboxButton.dataset.action as any);const approvalButton=el.closest<HTMLButtonElement>(".approval-action");if(approvalButton?.dataset.id&&approvalButton.dataset.action)void decideApproval(approvalButton.dataset.id,approvalButton.dataset.action as any);});customerSearch.addEventListener("input",()=>void renderCustomers(customerSearch.value));$("#new-task").addEventListener("click",()=>resetWorkspace(true));$("#open-inbox").addEventListener("click",()=>$("#inbox").scrollIntoView({behavior:"smooth"}));$("#clear-history").addEventListener("click",()=>void clearTaskHistory().then(()=>refreshAfterReset("Task history cleared. Sample business data preserved.")));$("#restore-business-data").addEventListener("click",()=>void restoreSampleBusinessData().then(()=>refreshAfterReset("Sample business data restored. Task history preserved.")));$("#reset-entire-demo").addEventListener("click",()=>{if(confirm("Reset all local demo business data, task history, inbox decisions and approvals?"))void resetEntireDemo().then(()=>refreshAfterReset("Entire demo reset to deterministic seed."));});$("#copy-evidence").addEventListener("click",()=>void navigator.clipboard.writeText(latestEvidence));$("#view-evidence").addEventListener("click",()=>{evidenceDetails.open=true;if(matchMedia("(max-width:760px)").matches)openDrawer();});openTrustDrawerButton.addEventListener("click",openDrawer);closeTrustDrawerButton.addEventListener("click",closeDrawer);drawerOverlay.addEventListener("click",closeDrawer);document.addEventListener("keydown",e=>{if(e.key==="Escape"&&trustDrawer.classList.contains("open"))closeDrawer();});}

export async function bootstrapDashboard(){datasetSnapshot.textContent=`Demo Business Data · ${DEMO_COMPANY_NAME} · Snapshot ${dateLabel()} · Local IndexedDB`;businessDataDetail.textContent=`${DEMO_COMPANY_NAME} · demo-business-v1 · Snapshot ${dateLabel()}`;await initializeBusinessWorld();bindEvents();await renderAll();resetWorkspace(false);}
