import type { WorkRepository } from "../data/work-repository";
import type { BusinessApproval, BusinessEvidence, BusinessInboxItem, BusinessTask, DraftAction, TaskEvent } from "../data/models";

async function appendEvent(work:WorkRepository,taskId:string,type:TaskEvent["type"],message:string,suffix:string):Promise<void>{const existing=await work.listTaskEvents(taskId);const max=existing.reduce((m,e)=>Math.max(m,Date.parse(e.occurredAt)),Date.now()-1);const occurredAt=new Date(max+1).toISOString();await work.appendTaskEvent({id:`event-${taskId}-${max+1}-${suffix}`,taskId,type,occurredAt,message});}
export async function createLocalDemoApproval(work:WorkRepository,input:{title:string;customerQuery:string;snapshotLabel:string}){
  const now=new Date().toISOString(),taskId=`task-${Date.now()}`,approvalId=`approval-${Date.now()}`;
  const task:BusinessTask={id:taskId,title:input.title,intent:"approval-demo",customerQuery:input.customerQuery,status:"needs-approval",createdAt:now,updatedAt:now,approvalId};
  const approval:BusinessApproval={id:approvalId,taskId,state:"pending",title:`Prepare ${input.customerQuery} follow-up draft`,what:`Resume a read-only ${input.customerQuery} receivables review and create a local follow-up draft.`,why:"Demonstrate that Alex pauses before manager-controlled work.",affected:`${input.customerQuery} demo data · ${input.snapshotLabel}`,impact:"Local Demo Simulation only. No external system changed.",createdAt:now,simulation:true};
  const inbox:BusinessInboxItem={id:`inbox-${approvalId}`,type:"approval-required",severity:"warning",relatedEntityType:"approval",relatedEntityId:approvalId,createdAt:now,status:"open",title:`Approval required: ${input.customerQuery} follow-up draft`,detail:"Alex paused before continuing. Local simulation; no external system changed."};
  await work.createTask(task);await appendEvent(work,taskId,"CREATED","Task created","created");await appendEvent(work,taskId,"ROUTED","Routed to local approval simulation","routed");await appendEvent(work,taskId,"NEEDS_APPROVAL","Waiting for manager approval","approval");await work.saveApproval(approval);await work.saveInboxItem(inbox);return{task,approval};
}
export async function approveLocalDemo(work:WorkRepository,approvalId:string){const approval=await work.getApproval(approvalId);if(!approval||approval.state!=="pending")return undefined;const task=await work.getTask(approval.taskId);if(!task)return undefined;const now=new Date().toISOString();approval.state="approved";approval.decidedAt=now;task.status="running";task.updatedAt=now;await work.saveApproval(approval);await work.updateTask(task);await appendEvent(work,task.id,"APPROVED","Manager approved local demo simulation","approved");await appendEvent(work,task.id,"RESUMED","Alex resumed work after approval","resumed");await work.updateInboxStatus(`inbox-${approval.id}`,"resolved","Approved and resumed");const draft:DraftAction={id:`draft-${task.id}`,taskId:task.id,type:"customer-follow-up",createdAt:now,status:"draft",content:{customer:task.customerQuery,simulation:true,note:"Local draft only; no email sent."}};await work.saveDraftAction(draft);return{task,approval,draft};}
export async function rejectLocalDemo(work:WorkRepository,approvalId:string){const approval=await work.getApproval(approvalId);if(!approval||approval.state!=="pending")return undefined;const task=await work.getTask(approval.taskId);if(!task)return undefined;const now=new Date().toISOString();approval.state="rejected";approval.decidedAt=now;task.status="blocked";task.updatedAt=now;task.summary={reason:"Rejected by manager. No business execution occurred."};await work.saveApproval(approval);await work.updateTask(task);await appendEvent(work,task.id,"REJECTED","Manager rejected the local demo approval","rejected");const evidence:BusinessEvidence={id:`evidence-${task.id}-rejected`,taskId:task.id,type:"approval.rejected",source:"local-demo",createdAt:now,data:{reason:"Manager rejected. No external system changed."}};await work.saveEvidence(evidence);await work.updateInboxStatus(`inbox-${approval.id}`,"resolved","Rejected by manager");return{task,approval,evidence};}
